// <auto-generated />
using System;
using FinRiskLensAI.Data.DbContextEDMX;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinRiskLensAI.Data.Migrations.SqlServer
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824094035_Add_BankAdmin_And_ScoreSummary")]
    partial class Add_BankAdmin_And_ScoreSummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinRiskLensAI.Core.Models.AccountAggregator.AAConsentReqModel", b =>
                {
                    b.Property<int>("ConsentReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsentReqId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("channelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("consentHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("custId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("encryptedFiuId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("encryptedRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requestDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("rid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ts")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("uan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsentReqId");

                    b.HasIndex("consentHandle");

                    b.HasIndex("transactionId");

                    b.HasIndex("uan");

                    b.ToTable("t_AAConsentRequest", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.AccountAggregator.AccAggreTokenModel", b =>
                {
                    b.Property<int>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenID"));

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("rid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TokenID");

                    b.ToTable("t_AccAggreToken", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Admin.AdmBankLogin", b =>
                {
                    b.Property<int>("AdmBankLoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmBankLoginID"));

                    b.Property<string>("BankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BranchAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pin")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdmBankLoginID");

                    b.HasIndex("IfscCode");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ADM_BankLogin", (string)null);

                    b.HasData(
                        new
                        {
                            AdmBankLoginID = 1,
                            BankName = "IDBI Bank",
                            BranchAddress = "IDBI Bank Ltd, Sitabuldi Main Road, Nagpur",
                            BranchCode = "000472",
                            BranchName = "Sitabuldi, Nagpur",
                            City = "Nagpur",
                            CreatedAt = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Designation = "Credit Manager",
                            Email = "bankadmin@idbi.co.in",
                            FailedLoginCount = 0,
                            FullName = "IDBI Bank Administrator",
                            IfscCode = "IBKL0000472",
                            IsActive = true,
                            MobileNumber = "9000000001",
                            PasswordHash = "AQAAAAIAAYagAAAAEIPBkSkagDEeRELmgDgCxJZinAKg/KQmO6hPeDdLe8u4haJi+IM8JF0dUZEbZgkqkA==",
                            Pin = "440012",
                            Role = "BankAdmin",
                            State = "Maharashtra",
                            UpdatedAt = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "bankadmin"
                        });
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Admin.AdmLogin", b =>
                {
                    b.Property<int>("AdmLoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmLoginID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdmLoginID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ADM_Login", (string)null);

                    b.HasData(
                        new
                        {
                            AdmLoginID = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Email = "admin@finrisklens.ai",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAECqQCLDS1XMpIauPSCY8GXjyewL5WfquYrxarGU82tSJ8a+XzMzhzkdWS+Dfu1hVcA==",
                            Role = "SuperAdmin",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.GST.GSTR2And3BResponceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FilingPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GSTINNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GSTR2BRequestData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("2BRequestData");

                    b.Property<string>("GSTR2BResponseData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("2BResponseData");

                    b.Property<string>("GSTR3BRequestData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("3BRequestData");

                    b.Property<string>("GSTR3BResponseData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("3BResponseData");

                    b.Property<string>("UdyamNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("UdyamNumber");

                    b.ToTable("t_GSTR2And3BResponce", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.MsmeEnquiry", b =>
                {
                    b.Property<int>("MsmeEnquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MsmeEnquiryID"));

                    b.Property<DateTime?>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Block")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateOfCommencement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfIncorporation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DicName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Flat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GstinNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRegister")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MajorActivity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MsmeDfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameOfBuilding")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameOfEnterprise")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OrganizationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Road")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SocialCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Village")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MsmeEnquiryID");

                    b.HasIndex("Uan")
                        .IsUnique();

                    b.ToTable("t_MsmeEnquiry", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.MsmeLocation", b =>
                {
                    b.Property<int>("MsmeLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MsmeLocationID"));

                    b.Property<string>("Building")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Line1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MsmeEnquiryID")
                        .HasColumnType("int");

                    b.Property<string>("Pin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Road")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Village")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MsmeLocationID");

                    b.HasIndex("MsmeEnquiryID");

                    b.ToTable("t_MsmeLocations", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.MsmeNicCode", b =>
                {
                    b.Property<int>("MsmeNicCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MsmeNicCodeID"));

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MsmeEnquiryID")
                        .HasColumnType("int");

                    b.Property<string>("Nic2Digit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nic4Digit")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nic5Digit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MsmeNicCodeID");

                    b.HasIndex("MsmeEnquiryID");

                    b.ToTable("t_MsmeNicCodes", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.UserRegistrationModel", b =>
                {
                    b.Property<int>("UserRegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRegistrationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GstinNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("MsmeEnquiryID")
                        .HasColumnType("int");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UdyamNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRegistrationID");

                    b.HasIndex("GstinNumber");

                    b.HasIndex("MobileNumber");

                    b.HasIndex("MsmeEnquiryID");

                    b.HasIndex("PanNumber");

                    b.HasIndex("UdyamNumber");

                    b.ToTable("t_UserRegistration", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Scoring.MsmeScoreSummary", b =>
                {
                    b.Property<int>("MsmeScoreSummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MsmeScoreSummaryID"));

                    b.Property<decimal>("AnnualTurnover")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("CashflowTrendSlope")
                        .HasColumnType("float");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DimensionsExcludedCount")
                        .HasColumnType("int");

                    b.Property<double>("HeuristicScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsAnomalous")
                        .HasColumnType("bit");

                    b.Property<double>("MlCalibratedScore")
                        .HasColumnType("float");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MonthlySurplus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<string>("ScoreBand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TermLoanCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TopProductName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TopProductScheme")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalIndicativeEligibility")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Uan")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WorkingCapitalLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MsmeScoreSummaryID");

                    b.HasIndex("OverallScore");

                    b.HasIndex("ScoreBand");

                    b.HasIndex("Uan")
                        .IsUnique();

                    b.ToTable("t_MsmeScoreSummary", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Universal.StaticResponseModel", b =>
                {
                    b.Property<int>("StaticResponcesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaticResponcesID"));

                    b.Property<string>("DINResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GST2BResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GST3BResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNumberResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITRNumberResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCAResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNumberResponce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UdyamNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UdyamNumberResponce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaticResponcesID");

                    b.HasIndex("UdyamNumber")
                        .IsUnique()
                        .HasFilter("[UdyamNumber] IS NOT NULL");

                    b.ToTable("m_StaticResponces", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.User_Activity.UserOtpModel", b =>
                {
                    b.Property<int>("UserOtpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserOtpID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("MsmeEnquiryID")
                        .HasColumnType("int");

                    b.Property<string>("OTP")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRegistrationID")
                        .HasColumnType("int");

                    b.HasKey("UserOtpID");

                    b.HasIndex("MsmeEnquiryID");

                    b.HasIndex("UserRegistrationID");

                    b.ToTable("t_UserOtp", (string)null);
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.MsmeLocation", b =>
                {
                    b.HasOne("FinRiskLensAI.Core.Models.Onboarding.MsmeEnquiry", "MsmeEnquiry")
                        .WithMany("Locations")
                        .HasForeignKey("MsmeEnquiryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MsmeEnquiry");
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.MsmeNicCode", b =>
                {
                    b.HasOne("FinRiskLensAI.Core.Models.Onboarding.MsmeEnquiry", "MsmeEnquiry")
                        .WithMany("NicCodes")
                        .HasForeignKey("MsmeEnquiryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MsmeEnquiry");
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.UserRegistrationModel", b =>
                {
                    b.HasOne("FinRiskLensAI.Core.Models.Onboarding.MsmeEnquiry", "MsmeEnquiry")
                        .WithMany()
                        .HasForeignKey("MsmeEnquiryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MsmeEnquiry");
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.User_Activity.UserOtpModel", b =>
                {
                    b.HasOne("FinRiskLensAI.Core.Models.Onboarding.MsmeEnquiry", "MsmeEnquiry")
                        .WithMany()
                        .HasForeignKey("MsmeEnquiryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinRiskLensAI.Core.Models.Onboarding.UserRegistrationModel", "UserRegistration")
                        .WithMany()
                        .HasForeignKey("UserRegistrationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MsmeEnquiry");

                    b.Navigation("UserRegistration");
                });

            modelBuilder.Entity("FinRiskLensAI.Core.Models.Onboarding.MsmeEnquiry", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("NicCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
